### ISSUE TITLE
Add requirements / dependency info so that binder can run the tutorial successfully

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python-docs#17]
It would be pretty cool to allow users who come to the repo to launch the tutorial notebooks in [binder](https://mybinder.org/). We could add a button to launch it to the readme now, but when you try to run the first step of any notebook it fails because it can't find the intermine package.

If we add requirements details to the repo, as per the guidance here: http://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder binder will know how to find the intermine python client, and people will be able to play with our notebook tutorials without having to clone the repo and install jupyter themselves. This would be pretty nifty!

**Comment by julie-sullivan** [comment]
@nupurgunwant Maybe take a look? Would be useful, and seems easy enough.

**Comment by nupurgunwant** [comment]
Yes, its really useful 👍

**Comment by yochannah** [comment]
This is fixed https://github.com/intermine/intermine-ws-python-docs/commit/4dd505e6aa84a5a208b6053d118c6ef238650b1e
