### ISSUE TITLE
consider renaming the tutorials to start with a number so that they are in order

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python-docs#20]
the tutorials currently present in alphabetic order rather than tutorial order. @raoofphysics pointed this out and suggested using `git mv` to preserve history of the files when we rename.

**Comment by omi10859** [comment]
I too thought about this as its bit difficult to find next tutorial or any sometimes. It would be better if they start with numbers and are arranged well.
If no one is picking up, I can do this :D

**Comment by yochannah** [comment]
@omi10859 you are welcome to! My only worry is that we have quite a few PRs we haven't had time to review yet and there might be some merge conflicts. Maybe we could ping you once they're merged and it's safe to go ahead?

**Comment by omi10859** [comment]
Yeah sure. If you need help with something else just let me know!!

**Comment by julie-sullivan** [comment]
Also, please add links to the tutorials.

**Comment by julie-sullivan** [comment]
Also, it's fine to rename them now!

**Comment by omi10859** [comment]
@julie-sullivan I don't totally understand 

> Also, please add links to the tutorials. 

which links you are talking about

**Comment by julie-sullivan** [comment]
Sorry! The README lists the tutorials but doesn't link to them.

**Comment by omi10859** [comment]
mybinder link? 
like for first tutorial there should be link of [this](https://hub.mybinder.org/user/intermine-inter--ws-python-docs-l5aqjyrt/notebooks/first-tutorial.ipynb)?

**Comment by julie-sullivan** [comment]
I added the links to the tutorials here: 1c8f8586430003a6ed75d765b46d02e10dc67af0

**Comment by omi10859** [comment]
Now, We can close this issue now :)
