### ISSUE TITLE
List upload - specify an organism

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine-ws-python-docs#33]
Lots of people want to upload using gene symbols but gene symbols aren't unique to an organism -- so we need to be able to specify organism on list upload.

**Comment by nkengawoh** [comment]
@julie-sullivan @FlyMine @nupurgunwant Is it Ok if I work on this?

**Comment by julie-sullivan** [comment]
okay with me!

**Comment by nkengawoh** [comment]
@julie-sullivan Sorry for the huge delay. I was caught up with a lot .
For this issue, Here is the plan I have:

- Add organism name in the create_list method
If the organism name is given, do the following
- create query with the given parameters(including the organism name)
- create a list from the generated query

Please If I am wrong or if there is a better way to satisfy the requirements, let me know.
I think writing code without the approval of my thought-process and algorithm will be a waste of time and energy.

**Comment by julie-sullivan** [comment]
that sounds sensible to me!

**Comment by nkengawoh** [comment]
@julie-sullivan Ok,
Is it ok if I go ahead with this idea on the implementation?

**Comment by julie-sullivan** [comment]
@nkengawoh Yes, go ahead!

**Comment by nkengawoh** [comment]
@julie-sullivan 
Please could you review issue: https://github.com/intermine/intermine-ws-python/pull/36 ?

**Comment by julie-sullivan** [comment]
@nkengawoh Sure! Can you fix the errors listed here first? https://github.com/intermine/intermine-ws-python/pull/36#issuecomment-466766649
